# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time_recorded',
            field=models.DateTimeField(),
        ),
    ]
