# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20160201_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='temp_value',
            field=models.FloatField(),
        ),
    ]
